name: Update Recent Repositories

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List recent repositories
        uses: Readme-Workflows/recent-repos@main
        with:
          username: BhavanaNannuru
          max_repos: 5
          sort: pushed
          exclude: "BhavanaNannuru"
