name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Update recent repos/activity
        uses: theboi/github-update-readme@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: "Recent Public Projects"
          subhead: "Shows your most recently active repositories."
          footer: "📈 Updated automatically by GitHub Actions"
          repoCount: 5
          reposPerRow: 5
          imageSize: 150
